# Generated by Django 5.0.8 on 2025-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
