# Generated by Django 5.0.8 on 2025-08-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_alter_history_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("model", "Model")], max_length=20
            ),
        ),
    ]
