# Generated by Django 5.0.8 on 2025-08-14 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_news"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegramuser",
            old_name="last_active",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="date_joined",
        ),
        migrations.AddField(
            model_name="history",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
