# Generated by Django 5.0.8 on 2025-08-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_rename_last_active_telegramuser_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenAISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_name",
                    models.CharField(default="gemini-2.0-flash", max_length=100),
                ),
                ("temperature", models.FloatField(default=0.5)),
                ("top_k", models.IntegerField(default=2)),
                ("top_p", models.FloatField(default=0.5)),
                ("max_output_tokens", models.IntegerField(blank=True, null=True)),
                ("seed", models.IntegerField(blank=True, null=True)),
                ("tools", models.JSONField(default=list)),
                ("safety_settings", models.JSONField(default=list)),
                ("response_modalities", models.JSONField(blank=True, default=list)),
                (
                    "response_mime_type",
                    models.CharField(default="application/json", max_length=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genai_settings",
                        to="bot.telegramuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
