# Generated by Django 5.0.8 on 2025-08-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_genaisettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genaisettings",
            name="response_mime_type",
        ),
        migrations.RemoveField(
            model_name="genaisettings",
            name="response_modalities",
        ),
    ]
