# Generated by Django 5.0.8 on 2025-08-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_remove_genaisettings_response_mime_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenAISetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_name",
                    models.CharField(
                        default="gemini-2.0-flash",
                        max_length=100,
                        verbose_name="(Google AI) Model Name",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.5, verbose_name="Temperature"),
                ),
                ("top_k", models.IntegerField(default=2, verbose_name="Top K")),
                ("top_p", models.FloatField(default=0.5, verbose_name="Top P")),
                (
                    "max_output_tokens",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Max Output Tokens"
                    ),
                ),
                (
                    "seed",
                    models.IntegerField(blank=True, null=True, verbose_name="Seed"),
                ),
                ("tools", models.JSONField(default=list, verbose_name="Tools")),
                (
                    "safety_settings",
                    models.JSONField(default=list, verbose_name="Safety Settings"),
                ),
            ],
            options={
                "verbose_name": "GenAI Setting",
                "verbose_name_plural": "GenAI Settings",
                "db_table": "genai_ai_settings",
            },
        ),
        migrations.CreateModel(
            name="New",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Is Published"),
                ),
            ],
            options={
                "verbose_name": "New",
                "verbose_name_plural": "News",
                "db_table": "news",
            },
        ),
        migrations.RemoveField(
            model_name="genaisettings",
            name="user",
        ),
        migrations.DeleteModel(
            name="News",
        ),
        migrations.AlterModelOptions(
            name="history",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "History",
                "verbose_name_plural": "Histories",
            },
        ),
        migrations.RenameIndex(
            model_name="history",
            new_name="histories_telegra_1511f5_idx",
            old_name="bot_history_telegra_7429fe_idx",
        ),
        migrations.AlterField(
            model_name="history",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="history",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="history_files/", verbose_name="File"
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "TEXT"),
                    ("image", "Image"),
                    ("document", "Document"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                ],
                default="text",
                max_length=20,
                verbose_name="Message Type",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("model", "Model")],
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="access_token",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Access Token (Google AI)",
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="user_id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, unique=True, verbose_name="User ID"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Username"
            ),
        ),
        migrations.AlterModelTable(
            name="history",
            table="histories",
        ),
        migrations.AlterModelTable(
            name="telegramuser",
            table="telegram_users",
        ),
        migrations.AddField(
            model_name="genaisetting",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genai_settings",
                to="bot.telegramuser",
            ),
        ),
        migrations.DeleteModel(
            name="GenAISettings",
        ),
    ]
