# Generated by Django 5.0.8 on 2025-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0008_genaisetting_new_remove_genaisettings_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genaisetting",
            name="model_name",
            field=models.CharField(
                choices=[("gemini-2.0-flash", "Gemini 2.0-Flash")],
                default="gemini-2.0-flash",
                max_length=100,
                verbose_name="(Google AI) Model Name",
            ),
        ),
    ]
